#!/bin/bash

usage() {
  echo "Usage: $0 -l <length>"
  echo "  -l <length> Specify the length of the password to generate"
  exit 1
}

while getopts ":l:" opt; do
  case ${opt} in
    l )
      length=$OPTARG
      if ! [[ "$length" =~ ^[0-9]+$ ]] || [ "$length" -le 0 ]; then
        usage
      fi
      ;;
    \? )
      echo "Invalid option: -$OPTARG" >&2
      usage
      ;;
    : )
      echo "Invalid option: -$OPTARG requires an argument" >&2
      usage
      ;;
  esac
done
shift $((OPTIND -1))

if [ -z "$length" ]; then
  usage
fi

password=$(head -c "$length" /dev/urandom | base64 | head -c "$length")

echo "$password"